import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { finishAll } from '../scripts/lib/finish.ts';
import { syncAll } from '../scripts/lib/sync.ts';
import type { SyncOptions, SyncResult, Vault } from '../scripts/lib/types.ts';
import { SCAFFOLD, TODAY, csvOf, fixtureText, jobPath, makeVaults, readJob, row, snapshot } from './helpers.ts';

process.env.TZ = 'America/New_York';

const ACME = 'Acme – Staff Frontend Engineer';
const INITECH = 'Initech – Staff Frontend Engineer';

const stateWith = (loops: string) => `# Coaching State\n\n## Interview Loops (active)\n\n${loops}\n## JD Analyses\n`;
const writeState = (vault: Vault, text: string) => writeFileSync(join(vault.dir, '..', 'coaching_state.md'), text);
const readConfig = (vault: Vault) => JSON.parse(readFileSync(join(vault.dir, '.teal-sync.json'), 'utf8'));
const vaultOf = (result: SyncResult, vault: Vault) => result.vaults.find((v) => v.vaultDir === vault.dir)!;

function run(csv: string, all: Vault[], options: Partial<SyncOptions> = {}) {
  const opts = { today: TODAY, ...options };
  return finishAll(syncAll(csv, all, opts), all, opts);
}

const ACME_INTERVIEWING = stateWith(
  '### Acme\n- Status: Interviewing\n- Rounds completed: Recruiter screen (09-09)\n- Next round: HM, 09-16\n- Stories used: S001, S003\n',
);

describe('loop mirror', () => {
  it('writes loop_status and a DERIVED:loop block from this root\'s coaching state', () => {
    const { ic, all } = makeVaults();
    writeState(ic, ACME_INTERVIEWING);
    const result = run(csvOf([
      row({ id: 't1', statusName: 'interviewing' }),
      row({ id: 't2', company_name: 'Initech' }),
    ]), all);

    const acme = readJob(ic, ACME);
    assert.equal(acme.fm.loop_status, 'Interviewing');
    assert.ok(acme.body.startsWith('<!-- DERIVED:loop START. AUTO-GENERATED by teal-sync. DO NOT HAND-EDIT. Last regen: 2026-09-12 -->\n'
      + 'Status: Interviewing · Rounds: Recruiter screen (09-09) · Next: HM, 09-16 · Stories: S001, S003\n'
      + '<!-- DERIVED:loop END -->\n'));
    assert.ok(acme.body.endsWith(SCAFFOLD));

    const initech = readJob(ic, INITECH);
    assert.equal(initech.fm.loop_status, null);
    assert.equal(initech.body, '');

    assert.equal(vaultOf(result, ic).jobs.find((j) => j.tealId === 't1')?.loopStatus, 'Interviewing');
  });

  it('keeps user text when the loop changes, and removes the block when the loop is gone', () => {
    const { ic, all } = makeVaults();
    const csv = csvOf([row({ id: 't1', statusName: 'interviewing' })]);
    writeState(ic, ACME_INTERVIEWING);
    run(csv, all);

    const path = jobPath(ic, ACME);
    writeFileSync(path, `${readFileSync(path, 'utf8')}\nMy reflections.\n`);
    writeState(ic, stateWith('### Acme\n- Status: Offer\n'));
    run(csv, all);
    let acme = readJob(ic, ACME);
    assert.equal(acme.fm.loop_status, 'Offer');
    assert.match(acme.body, /^<!-- DERIVED:loop START[^\n]*\nStatus: Offer\n<!-- DERIVED:loop END -->\n\n## Why this role/);
    assert.ok(acme.body.endsWith('\nMy reflections.\n'));

    writeState(ic, stateWith(''));
    run(csv, all);
    acme = readJob(ic, ACME);
    assert.equal(acme.fm.loop_status, null);
    assert.ok(!acme.body.includes('DERIVED:loop'));
    assert.ok(acme.body.startsWith('## Why this role'));
  });

  it('keeps the regen date when nothing in the block changed', () => {
    const { ic, all } = makeVaults();
    const csv = csvOf([row({ id: 't1', statusName: 'interviewing' })]);
    writeState(ic, ACME_INTERVIEWING);
    run(csv, all);
    run(csv, all, { today: '2026-09-13' });
    assert.match(readJob(ic, ACME).body, /Last regen: 2026-09-12/);
  });

  it('warns and carries on when coaching_state.md is missing', () => {
    const { ic, all } = makeVaults();
    const result = run(csvOf([row({ id: 't1', statusName: 'applied' })]), all);
    assert.ok(vaultOf(result, ic).warnings.some((w) => w.includes('coaching_state.md')));
    assert.equal(readJob(ic, ACME).fm.loop_status, null);
  });
});

describe('feedback queue and config', () => {
  it('queues feedback in .teal-sync.json, sets lastSync, and drops the old proposal keys', () => {
    const { manager, ic, all } = makeVaults();
    writeFileSync(join(ic.dir, '.teal-sync.json'), JSON.stringify({ ...readConfig(ic), pendingProposals: [], dismissedProposals: ['t9:Applied'] }));
    const result = run(csvOf([row({ id: 't1', url: 'https://example.com/jobs/1' })]), all);

    const config = readConfig(ic);
    assert.equal(config.lastSync, TODAY);
    assert.deepEqual(config.pendingFeedback, [{
      tealId: 't1', company: 'Acme', role: 'Staff Frontend Engineer', url: 'https://example.com/jobs/1', from: null, to: 'bookmarked', seenOn: TODAY,
    }]);
    assert.ok(!('pendingProposals' in config) && !('dismissedProposals' in config));
    assert.equal(config.things.project, 'Example – D', 'other keys survive');
    assert.deepEqual(vaultOf(result, ic).feedback, config.pendingFeedback);
    assert.equal(vaultOf(result, ic).feedbackMessage, "I'm interested in a new job description: Acme – Staff Frontend Engineer (https://example.com/jobs/1)");

    assert.equal(readConfig(manager).lastSync, TODAY);
    assert.deepEqual(readConfig(manager).pendingFeedback, []);
    assert.equal(vaultOf(result, manager).feedbackMessage, null);
  });

  it('keeps queued feedback across syncs and merges moves of the same job', () => {
    const { ic, all } = makeVaults();
    run(csvOf([row({ id: 't1', statusName: 'applied' })]), all);
    writeFileSync(join(ic.dir, '.teal-sync.json'), JSON.stringify({ ...readConfig(ic), pendingFeedback: [] }));

    run(csvOf([row({ id: 't1', statusName: 'interviewing' })]), all, { today: '2026-09-13' });
    run(csvOf([row({ id: 't1', statusName: 'negotiating' }), row({ id: 't2', company_name: 'Initech' })]), all, { today: '2026-09-14' });
    assert.deepEqual(readConfig(ic).pendingFeedback.map((i: { tealId: string; from: string | null; to: string; seenOn: string }) => [i.tealId, i.from, i.to, i.seenOn]), [
      ['t1', 'applied', 'negotiating', '2026-09-13'],
      ['t2', null, 'bookmarked', '2026-09-14'],
    ]);
  });

  it('writes nothing on a dry run but still reports', () => {
    const { root, ic, all } = makeVaults();
    const before = snapshot(root);
    const result = run(csvOf([row({ id: 't1', statusName: 'applied' })]), all, { dryRun: true });
    assert.deepEqual(snapshot(root), before);
    assert.equal(vaultOf(result, ic).feedback.length, 1);
  });

  it('warns when several loops match a job', () => {
    const { ic, all } = makeVaults();
    writeState(ic, stateWith('### Acme — Design Systems\n- Status: Applied\n\n### Acme — Platform\n- Status: Interviewing\n'));
    const result = run(csvOf([row({ id: 't1', statusName: 'applied' })]), all);
    assert.ok(vaultOf(result, ic).warnings.some((w) => /Several loops match Acme/.test(w)), vaultOf(result, ic).warnings.join('\n'));
  });

  it('leaves an aborted vault\'s config alone', () => {
    const { ic, all } = makeVaults();
    const four = ['Acme', 'Initech', 'Hooli', 'Tyrell'].map((company, n) => row({ id: `t${n}`, company_name: company }));
    run(csvOf(four), all);
    const result = run(csvOf(four.slice(0, 1)), all, { today: '2026-09-13' });
    assert.equal(vaultOf(result, ic).aborted, true);
    assert.equal(readConfig(ic).lastSync, TODAY);
    assert.match(vaultOf(result, ic).summary, /aborted/i);
  });

  it('is idempotent', () => {
    const { root, ic, all } = makeVaults();
    writeState(ic, ACME_INTERVIEWING);
    const csv = csvOf([row({ id: 't1', statusName: 'interviewing' }), row({ id: 't2', company_name: 'Initech', statusName: 'applied' })]);
    run(csv, all);
    const first = snapshot(root);
    run(csv, all);
    assert.deepEqual(snapshot(root), first);
  });
});

describe('digest', () => {
  it('summarizes the fixture with no coach-command suggestions', () => {
    const { manager, ic, all } = makeVaults();
    const result = run(fixtureText(), all);
    assert.equal(result.header, 'Teal sync: 10 jobs (3 manager, 7 IC); 10 new, 0 status changes');

    const digest = vaultOf(result, manager).digest;
    assert.ok(digest.includes('NEW  Globex (Sr. Manager, Digital Experience) → interviewing'), digest.join('\n'));
    assert.ok(digest.includes("FEED I've started interviewing for Globex – Sr. Manager, Digital Experience"), digest.join('\n'));
    assert.ok(!digest.some((line) => /suggest: (?!create|complete)/.test(line)), digest.join('\n'));
    assert.match(vaultOf(result, ic).summary, /^ic-web-dev-search: 7 new, .*7 for feedback/);
  });

  it('lists feedback for bookmarks and a to-do for applied jobs', () => {
    const { ic, all } = makeVaults();
    const result = run(csvOf([
      row({ id: 't1' }),
      row({ id: 't2', company_name: 'Initech', statusName: 'applied', applied_at: '2026-09-03T07:11:06Z', follow_up_at: '2026-09-14T04:00:00Z' }),
    ]), all);
    const digest = vaultOf(result, ic).digest;
    assert.ok(digest.includes('NEW  Acme (Staff Frontend Engineer) → bookmarked'), digest.join('\n'));
    assert.ok(digest.includes("FEED I'm interested in a new job description: Acme – Staff Frontend Engineer"), digest.join('\n'));
    assert.ok(digest.some((line) => /^DUE  Initech \(applied 09-03\), check-in 09-14 .*suggest: create Things to-do\?$/.test(line)), digest.join('\n'));
    assert.equal(vaultOf(result, ic).things.create[0].due, '2026-09-14');
  });

  it('reports status moves and archiving without flags on a later sync', () => {
    const { ic, all } = makeVaults();
    run(csvOf([row({ id: 't1' }), row({ id: 't2', company_name: 'Initech', statusName: 'interviewing' })]), all);
    writeState(ic, stateWith('### Acme\n- Status: Interviewing\n\n### Initech\n- Status: Interviewing\n'));
    const result = run(csvOf([
      row({ id: 't1', statusName: 'applying' }),
      row({ id: 't2', company_name: 'Initech', statusName: 'interviewing', archived_at: '2026-09-12T10:00:00Z' }),
    ]), all);
    const digest = vaultOf(result, ic).digest;
    assert.equal(result.header, 'Teal sync: 2 jobs (0 manager, 2 IC); 0 new, 2 status changes');
    assert.ok(digest.includes('MOVE Acme bookmarked → applying'), digest.join('\n'));
    assert.ok(digest.includes('GONE Initech (last: interviewing) → archived in Teal'), digest.join('\n'));
    assert.ok(digest.includes("FEED I'm no longer pursuing Initech – Staff Frontend Engineer (archived in Teal)"), digest.join('\n'));
    assert.ok(!digest.some((line) => /^(FLAG|LOOP)/.test(line)), digest.join('\n'));
    assert.match(vaultOf(result, ic).summary, /1 moved, 1 gone, 2 for feedback/);
  });
});
