import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { findLoop, loopLine, parseLoops, upsertLoopBlock } from '../scripts/lib/loops.ts';
import { SCAFFOLD } from './helpers.ts';

const STATE = `# Coaching State — Test

## Storybank
### S001 — Not a loop
- Status: Interviewing

## Interview Loops (active)

Note: \`Stories used per round\` in this section is the PRIMARY source.

### Globex
- Status: Interviewing
- Archetype: Platform
- Rounds completed: Recruiter screen (09-09)
- Round formats:
  - Round 1: Behavioral screen, 45min, recruiter
- Stories used:
  - Round 1: S001, S003
- Next round: HM, 09-16
- Fit verdict: Strong Fit

### Umbrella — Senior Software Engineer – Marketing
- Status: Researched
- Rounds completed: [list with dates]
- Next round: [date, format if known]

### Umbrella (Platform)
- Status: Decoded

## JD Analyses
### Initech — Staff Frontend Engineer
- Status: Interviewing

## Past Interview Loops
### Initrode
- Final round reached: onsite
- Outcome: rejected
`;

const OPEN = (date: string) => `<!-- DERIVED:loop START. AUTO-GENERATED by teal-sync. DO NOT HAND-EDIT. Last regen: ${date} -->`;
const block = (line: string, date = '2026-09-12') => `${OPEN(date)}\n${line}\n<!-- DERIVED:loop END -->\n`;

describe('parseLoops', () => {
  const loops = parseLoops(STATE);

  it('reads only Interview Loops and Past Interview Loops entries', () => {
    assert.deepEqual(loops.map((l) => l.heading), [
      'Globex', 'Umbrella — Senior Software Engineer – Marketing', 'Umbrella (Platform)', 'Initrode',
    ]);
  });

  it('reads status, rounds, next round, and multi-line stories', () => {
    assert.deepEqual(loops[0], {
      heading: 'Globex',
      company: 'Globex',
      qualifier: null,
      status: 'Interviewing',
      rounds: 'Recruiter screen (09-09)',
      nextRound: 'HM, 09-16',
      stories: 'Round 1: S001, S003',
      past: false,
    });
  });

  it('treats template placeholders as empty and splits role qualifiers', () => {
    assert.equal(loops[1].company, 'Umbrella');
    assert.equal(loops[1].qualifier, 'Senior Software Engineer – Marketing');
    assert.equal(loops[1].rounds, null);
    assert.equal(loops[1].nextRound, null);
    assert.equal(loops[2].company, 'Umbrella');
    assert.equal(loops[2].qualifier, 'Platform');
  });

  it('marks past loops Closed unless they say otherwise', () => {
    assert.equal(loops[3].status, 'Closed');
    assert.equal(loops[3].past, true);
  });

  it('returns nothing when there is no loops section', () => {
    assert.deepEqual(parseLoops('# State\n\n## Interview Loops (active)\nNone yet. Add via `research`.\n'), []);
    assert.deepEqual(parseLoops(''), []);
  });
});

describe('findLoop', () => {
  const loops = parseLoops(STATE);

  it('matches the company case-insensitively', () => {
    assert.equal(findLoop(loops, 'globex', 'Anything').loop?.heading, 'Globex');
  });

  it('does not match a longer company name', () => {
    assert.deepEqual(findLoop(parseLoops(STATE.replace('### Globex', '### Globexcorp')), 'Globex', 'x'), {
      loop: null, ambiguous: false,
    });
  });

  it('uses the role to pick between loops for the same company', () => {
    assert.equal(findLoop(loops, 'Umbrella', 'Senior Software Engineer – Marketing').loop?.qualifier, 'Senior Software Engineer – Marketing');
    assert.equal(findLoop(loops, 'Umbrella', 'Staff Platform Engineer').loop?.qualifier, 'Platform');
    assert.deepEqual(findLoop(loops, 'Umbrella', 'Designer'), { loop: null, ambiguous: true });
  });

  it('prefers an active loop over a past one', () => {
    const state = STATE.replace('## JD Analyses', '### Initrode\n- Status: Applied\n\n## JD Analyses');
    assert.equal(findLoop(parseLoops(state), 'Initrode', 'x').loop?.status, 'Applied');
  });
});

describe('loopLine', () => {
  const loops = parseLoops(STATE);

  it('joins the fields that have values', () => {
    assert.equal(loopLine(loops[0]), 'Status: Interviewing · Rounds: Recruiter screen (09-09) · Next: HM, 09-16 · Stories: Round 1: S001, S003');
    assert.equal(loopLine(loops[1]), 'Status: Researched');
  });
});

describe('upsertLoopBlock', () => {
  it('inserts the block at the top of an empty body', () => {
    assert.equal(upsertLoopBlock('', 'Status: Researched', '2026-09-12'), block('Status: Researched'));
  });

  it('inserts above existing text with a blank line between', () => {
    assert.equal(upsertLoopBlock(SCAFFOLD, 'Status: Applied', '2026-09-12'), `${block('Status: Applied')}\n${SCAFFOLD}`);
    assert.equal(upsertLoopBlock('\nNotes\n', 'Status: Applied', '2026-09-12'), `${block('Status: Applied')}\nNotes\n`);
  });

  it('replaces changed content and the regen date', () => {
    const body = `${block('Status: Applied')}\nNotes\n`;
    assert.equal(upsertLoopBlock(body, 'Status: Interviewing', '2026-09-13'), `${block('Status: Interviewing', '2026-09-13')}\nNotes\n`);
  });

  it('leaves the block alone when only the date would change', () => {
    const body = `${block('Status: Applied')}\nNotes\n`;
    assert.equal(upsertLoopBlock(body, 'Status: Applied', '2026-09-20'), body);
  });

  it('removes the block and its spacer when there is no loop', () => {
    assert.equal(upsertLoopBlock(`${block('Status: Applied')}\nNotes\n`, null, '2026-09-12'), 'Notes\n');
    assert.equal(upsertLoopBlock(block('Status: Applied'), null, '2026-09-12'), '');
    assert.equal(upsertLoopBlock('Notes\n', null, '2026-09-12'), 'Notes\n');
  });
});
