import { normalizeName } from './naming.ts';
import type { Loop } from './types.ts';

type LoopField = 'status' | 'rounds' | 'nextRound' | 'stories';

const LOOP_SECTION = /^## (Past )?Interview Loops\b/;
const ITEM = /^- ([^:]+):\s*(.*)$/;
const NESTED = /^\s+(?:- )?(\S.*)$/;
/** Unfilled schema template values like `[date, format if known]`, or explicit blanks. */
const PLACEHOLDER = /^\[.*\]$|^(none|n\/a|tbd|—|-)$/i;
/** `Company — Role`, `Company (Role)`, `Company: Role` */
const QUALIFIER = /\s+[—–-]\s+|\s*\(|:\s+/;
const FIELDS: [name: string, field: LoopField][] = [
  ['status', 'status'],
  ['rounds completed', 'rounds'],
  ['next round', 'nextRound'],
  ['stories used', 'stories'],
];
const BLOCK = /<!-- DERIVED:loop START[^\n]*-->\n([\s\S]*?)<!-- DERIVED:loop END -->\n?/;

/** Read `### <Company>` entries under `## Interview Loops` and `## Past Interview Loops` in coaching_state.md. */
export function parseLoops(stateText: string): Loop[] {
  const loops: Loop[] = [];
  let inSection = false;
  let past = false;
  let entry: { heading: string; values: Partial<Record<LoopField, string[]>> } | null = null;
  let field: LoopField | null = null;

  const close = () => {
    const current = entry;
    if (!current) return;
    const value = (key: LoopField) => cleanValue(current.values[key]);
    loops.push({
      heading: current.heading,
      ...splitHeading(current.heading),
      status: value('status') ?? (past ? 'Closed' : null),
      rounds: value('rounds'),
      nextRound: value('nextRound'),
      stories: value('stories'),
      past,
    });
    entry = null;
    field = null;
  };

  for (const line of stateText.split(/\r?\n/)) {
    if (line.startsWith('## ')) {
      close();
      const section = LOOP_SECTION.exec(line);
      inSection = section !== null;
      past = Boolean(section?.[1]);
      continue;
    }
    if (!inSection) continue;
    if (line.startsWith('### ')) {
      close();
      entry = { heading: line.slice(4).trim(), values: {} };
      continue;
    }
    if (!entry) continue;

    const item = ITEM.exec(line);
    if (item) {
      field = fieldFor(item[1]);
      if (field && item[2].trim()) (entry.values[field] ??= []).push(item[2].trim());
      continue;
    }
    const nested = NESTED.exec(line);
    if (nested && field) (entry.values[field] ??= []).push(nested[1].trim());
    else field = null;
  }
  close();
  return loops;
}

/** Find the loop for a job: company match, active over past, role qualifier to break ties. */
export function findLoop(loops: Loop[], company: string, role: string): { loop: Loop | null; ambiguous: boolean } {
  const target = normalizeName(company);
  const matches = loops.filter((loop) => normalizeName(loop.company) === target);
  const active = matches.filter((loop) => !loop.past);
  const pool = active.length > 0 ? active : matches;
  if (pool.length <= 1) return { loop: pool[0] ?? null, ambiguous: false };

  const roleText = normalizeName(role);
  const byRole = pool.filter((loop) => loop.qualifier !== null && roleText.includes(normalizeName(loop.qualifier)));
  return byRole.length === 1 ? { loop: byRole[0], ambiguous: false } : { loop: null, ambiguous: true };
}

/** `Status: Interviewing · Rounds: … · Next: … · Stories: …` */
export function loopLine(loop: Loop): string {
  const parts = [`Status: ${loop.status ?? 'unknown'}`];
  if (loop.rounds) parts.push(`Rounds: ${loop.rounds}`);
  if (loop.nextRound) parts.push(`Next: ${loop.nextRound}`);
  if (loop.stories) parts.push(`Stories: ${loop.stories}`);
  return parts.join(' · ');
}

/**
 * Put `line` in the note body's DERIVED:loop block (top of body), or remove the block when `line` is null.
 * An unchanged line keeps the old regen date so repeat syncs don't rewrite the note.
 */
export function upsertLoopBlock(body: string, line: string | null, today: string): string {
  const match = BLOCK.exec(body);
  if (line === null) {
    if (!match) return body;
    let end = match.index + match[0].length;
    if (body[end] === '\n') end += 1;
    return body.slice(0, match.index) + body.slice(end);
  }

  const block = `<!-- DERIVED:loop START. AUTO-GENERATED by teal-sync. DO NOT HAND-EDIT. Last regen: ${today} -->\n${line}\n<!-- DERIVED:loop END -->\n`;
  if (match) {
    if (match[1] === `${line}\n`) return body;
    return body.slice(0, match.index) + block + body.slice(match.index + match[0].length);
  }
  return body === '' || body.startsWith('\n') ? block + body : `${block}\n${body}`;
}

function fieldFor(key: string): LoopField | null {
  const name = key.trim().toLowerCase();
  return FIELDS.find(([field]) => name === field || name.startsWith(`${field} `))?.[1] ?? null;
}

function cleanValue(values: string[] | undefined): string | null {
  const kept = (values ?? []).map((value) => value.replace(/\s+/g, ' ')).filter((value) => !PLACEHOLDER.test(value));
  return kept.length > 0 ? kept.join('; ') : null;
}

function splitHeading(heading: string): { company: string; qualifier: string | null } {
  const match = QUALIFIER.exec(heading);
  if (!match) return { company: heading, qualifier: null };
  const qualifier = heading.slice(match.index + match[0].length).replace(/\)\s*$/, '').trim();
  return { company: heading.slice(0, match.index).trim(), qualifier: qualifier || null };
}
